all:
	webpack

	cp viewerbundle.js        ../../docubricksSite/WebContent/js/
	cp css/*.css              ../../docubricksSite/WebContent/css/
	cp images/*               ../../docubricksSite/WebContent/images/
	cp node_modules/react/dist/react.js node_modules/react-dom/dist/react-dom.js ../../docubricksSite/WebContent/js/

